# Generated by Django 6.0.1 on 2026-01-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attendance_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('current', 'Current'), ('completed', 'Completed'), ('failed', 'Failed'), ('repeated', 'Repeated')], default='current', max_length=20)),
                ('result_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('promoted', 'Promoted'), ('detained', 'Detained')], max_length=20, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.enrollment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
