# Generated by Django 6.0.1 on 2026-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_course_code_studentsemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsemester',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('not_started', 'Not Started'), ('current', 'Current'), ('completed', 'Completed'), ('failed', 'Failed'), ('repeated', 'Repeated')], default='current', max_length=20),
        ),
    ]
