# Generated by Django 6.0.1 on 2026-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_previousacademicrecord_studentdata_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousacademicrecord',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='previousacademicrecord',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previousacademicrecord',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
