# Generated by Django 6.0.1 on 2026-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_previousacademicrecord_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
