# Generated by Django 6.0.1 on 2026-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_studentdata_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousacademicrecord',
            name='grade',
        ),
        migrations.AddField(
            model_name='previousacademicrecord',
            name='university',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
