# Generated by Django 6.0.1 on 2026-01-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_blacklistedtoken_alter_user_role_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.TextField(unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='user_qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
