# Generated by Django 6.0.1 on 2026-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqr',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
